steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_GOOGLE_MAPS_API_KEY=${_VITE_GOOGLE_MAPS_API_KEY}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/reflection-journal-with-gemini-ai:latest'
      - '.'

images:
  - 'gcr.io/$PROJECT_ID/reflection-journal-with-gemini-ai:latest'
